"""Built-in subagent configurations."""

from .bash_agent import BASH_AGENT_CONFIG
from .general_purpose import GENERAL_PURPOSE_CONFIG
from .project_delivery import (
    ARCHITECT_AGENT_CONFIG,
    BACKEND_AGENT_CONFIG,
    DATA_AGENT_CONFIG,
    DELIVERY_AGENT_CONFIG,
    DESIGN_AGENT_CONFIG,
    DEVOPS_AGENT_CONFIG,
    DISCOVERY_AGENT_CONFIG,
    FRONTEND_AGENT_CONFIG,
    INTEGRATION_AGENT_CONFIG,
    PLANNER_AGENT_CONFIG,
    PROJECT_DELIVERY_SPECIALIST_CONFIGS,
    QA_AGENT_CONFIG,
)

__all__ = [
    "GENERAL_PURPOSE_CONFIG",
    "BASH_AGENT_CONFIG",
    "DISCOVERY_AGENT_CONFIG",
    "ARCHITECT_AGENT_CONFIG",
    "PLANNER_AGENT_CONFIG",
    "DESIGN_AGENT_CONFIG",
    "FRONTEND_AGENT_CONFIG",
    "BACKEND_AGENT_CONFIG",
    "INTEGRATION_AGENT_CONFIG",
    "DATA_AGENT_CONFIG",
    "DEVOPS_AGENT_CONFIG",
    "QA_AGENT_CONFIG",
    "DELIVERY_AGENT_CONFIG",
    "PROJECT_DELIVERY_SPECIALIST_CONFIGS",
]

# Registry of built-in subagents
BUILTIN_SUBAGENTS = {
    "general-purpose": GENERAL_PURPOSE_CONFIG,
    "bash": BASH_AGENT_CONFIG,
}

BUILTIN_SUBAGENTS.update({config.name: config for config in PROJECT_DELIVERY_SPECIALIST_CONFIGS})
