import logging
import mimetypes
import zipfile
from pathlib import Path
from urllib.parse import quote

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import FileResponse, PlainTextResponse, Response

from app.gateway.path_utils import resolve_thread_virtual_path

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api", tags=["artifacts"])

ACTIVE_CONTENT_MIME_TYPES = {
    "text/html",
    "application/xhtml+xml",
    "image/svg+xml",
}

PREVIEW_SECURITY_HEADERS = {
    "Content-Security-Policy": "sandbox allow-scripts allow-forms allow-downloads",
    "Referrer-Policy": "no-referrer",
    "X-Content-Type-Options": "nosniff",
}


def _build_content_disposition(disposition_type: str, filename: str) -> str:
    return f"{disposition_type}; filename*=UTF-8''{quote(filename)}"


def _merge_headers(*header_sets: dict[str, str] | None) -> dict[str, str]:
    headers: dict[str, str] = {}
    for header_set in header_sets:
        if header_set:
            headers.update(header_set)
    return headers


def _build_attachment_headers(filename: str, extra_headers: dict[str, str] | None = None) -> dict[str, str]:
    return _merge_headers(
        {"Content-Disposition": _build_content_disposition("attachment", filename)},
        extra_headers,
    )


def _build_inline_headers(filename: str, extra_headers: dict[str, str] | None = None) -> dict[str, str]:
    return _merge_headers(
        {"Content-Disposition": _build_content_disposition("inline", filename)},
        extra_headers,
    )


def _build_preview_headers(filename: str, extra_headers: dict[str, str] | None = None) -> dict[str, str]:
    return _build_inline_headers(filename, _merge_headers(PREVIEW_SECURITY_HEADERS, extra_headers))


def is_text_file_by_content(path: Path, sample_size: int = 8192) -> bool:
    try:
        with open(path, "rb") as f:
            chunk = f.read(sample_size)
            return b"\x00" not in chunk
    except Exception:
        return False


def _extract_file_from_skill_archive(zip_path: Path, internal_path: str) -> bytes | None:
    if not zipfile.is_zipfile(zip_path):
        return None

    try:
        with zipfile.ZipFile(zip_path, "r") as zip_ref:
            namelist = zip_ref.namelist()
            if internal_path in namelist:
                return zip_ref.read(internal_path)
            for name in namelist:
                if name.endswith("/" + internal_path) or name == internal_path:
                    return zip_ref.read(name)
            return None
    except (zipfile.BadZipFile, KeyError):
        return None


@router.get(
    "/threads/{thread_id}/artifacts/{path:path}",
    summary="Get Artifact File",
    description=(
        "Retrieve an artifact file generated by the AI agent. Text and binary files can be viewed inline. "
        "Active web content stays download-only by default, and can be rendered inside the sandboxed preview iframe with `preview=true`."
    ),
)
async def get_artifact(
    thread_id: str,
    path: str,
    request: Request,
    download: bool = False,
    preview: bool = False,
) -> Response:
    if ".skill/" in path:
        skill_marker = ".skill/"
        marker_pos = path.find(skill_marker)
        skill_file_path = path[: marker_pos + len(".skill")]
        internal_path = path[marker_pos + len(skill_marker) :]

        actual_skill_path = resolve_thread_virtual_path(thread_id, skill_file_path)

        if not actual_skill_path.exists():
            raise HTTPException(status_code=404, detail=f"Skill file not found: {skill_file_path}")
        if not actual_skill_path.is_file():
            raise HTTPException(status_code=400, detail=f"Path is not a file: {skill_file_path}")

        content = _extract_file_from_skill_archive(actual_skill_path, internal_path)
        if content is None:
            raise HTTPException(status_code=404, detail=f"File '{internal_path}' not found in skill archive")

        mime_type, _ = mimetypes.guess_type(internal_path)
        cache_headers = {"Cache-Control": "private, max-age=300"}
        download_name = Path(internal_path).name or actual_skill_path.stem

        if download:
            return Response(
                content=content,
                media_type=mime_type or "application/octet-stream",
                headers=_build_attachment_headers(download_name, cache_headers),
            )

        if preview and mime_type in ACTIVE_CONTENT_MIME_TYPES:
            return Response(
                content=content,
                media_type=mime_type or "application/octet-stream",
                headers=_build_preview_headers(download_name, cache_headers),
            )

        if mime_type in ACTIVE_CONTENT_MIME_TYPES:
            return Response(
                content=content,
                media_type=mime_type or "application/octet-stream",
                headers=_build_attachment_headers(download_name, cache_headers),
            )

        if mime_type and mime_type.startswith("text/"):
            return PlainTextResponse(content=content.decode("utf-8"), media_type=mime_type, headers=cache_headers)

        try:
            return PlainTextResponse(content=content.decode("utf-8"), media_type="text/plain", headers=cache_headers)
        except UnicodeDecodeError:
            return Response(content=content, media_type=mime_type or "application/octet-stream", headers=cache_headers)

    actual_path = resolve_thread_virtual_path(thread_id, path)
    logger.info(f"Resolving artifact path: thread_id={thread_id}, requested_path={path}, actual_path={actual_path}")

    if not actual_path.exists():
        raise HTTPException(status_code=404, detail=f"Artifact not found: {path}")
    if not actual_path.is_file():
        raise HTTPException(status_code=400, detail=f"Path is not a file: {path}")

    mime_type, _ = mimetypes.guess_type(actual_path)

    if download:
        return FileResponse(
            path=actual_path,
            filename=actual_path.name,
            media_type=mime_type,
            headers=_build_attachment_headers(actual_path.name),
        )

    if preview and mime_type in ACTIVE_CONTENT_MIME_TYPES:
        return FileResponse(
            path=actual_path,
            media_type=mime_type,
            headers=_build_preview_headers(actual_path.name),
        )

    if mime_type in ACTIVE_CONTENT_MIME_TYPES:
        return FileResponse(
            path=actual_path,
            filename=actual_path.name,
            media_type=mime_type,
            headers=_build_attachment_headers(actual_path.name),
        )

    if mime_type and mime_type.startswith("text/"):
        return PlainTextResponse(content=actual_path.read_text(encoding="utf-8"), media_type=mime_type)

    if is_text_file_by_content(actual_path):
        return PlainTextResponse(content=actual_path.read_text(encoding="utf-8"), media_type=mime_type)

    return Response(
        content=actual_path.read_bytes(),
        media_type=mime_type,
        headers=_build_inline_headers(actual_path.name),
    )
